
typedef struct
{
	long	Id;
	long	Hash;
	char*	Name;
	char*	Value;
} OSM_KEY_LIST;

extern OSM_FILL_STYLE	FillStyle[];
extern OSM_DRAW_STYLE	DrawStyle[];
extern OSM_KEY_LIST	KeyList2[];

enum KeyEnum
{
	KEY_NAME=1,
	KEY_REF,
	KEY_PLACE,
	KEY_AMENITY,
	KEY_HIGHWAY,
	KEY_LANDUSE,
	KEY_BARRIER,
	KEY_LEISURE
};

enum TagEnum
{
	TAG_HIGHWAY_MOTORWAY=1,
	TAG_HIGHWAY_TRUNK,
	TAG_HIGHWAY_PRIMARY,
	TAG_HIGHWAY_SECONDARY,
	TAG_HIGHWAY_TERTIARY,
	TAG_HIGHWAY_RESIDENTIAL,
	TAG_HIGHWAY_UNCLASSIFIED,
	TAG_HIGHWAY_SERVICE,
	TAG_HIGHWAY_TRACK,
	TAG_HIGHWAY_TRACKTYPE1,
	TAG_HIGHWAY_TRACKTYPE2,
	TAG_HIGHWAY_TRACKTYPE3,
	TAG_HIGHWAY_TRACKTYPE4,
	TAG_HIGHWAY_TRACKTYPE5,
	TAG_HIGHWAY_PATH,
	TAG_LANDUSE_RESIDENTIAL,
	TAG_LANDUSE_FOREST,
};

int PrefsInit(void);

